#ifndef GCHANNELMANAGER_GLOBAL_H
#define GCHANNELMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GCHANNELMANAGER_LIBRARY)
#define GCHANNELMANAGER_EXPORT Q_DECL_EXPORT
#else
#define GCHANNELMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // GCHANNELMANAGER_GLOBAL_H
